export type Point3 = [number, number, number];

export interface PlaneRestriction {
  point: Point3;
  inPlaneVector1: Point3;
  inPlaneVector2: Point3 | Record<string, number>;
}

export interface AnnotationMetadata {
  toolName: string;
  cameraFocalPoint?: Point3;
  viewPlaneNormal?: Point3;
  viewUp?: Point3;
  sliceIndex?: number;
  planeRestriction?: PlaneRestriction;
  referencedImageId?: string;
  cameraPosition?: Point3;
  segmentColor?: unknown;
  enabledElement?: unknown;
  [key: string]: unknown;
}

export interface AnnotationTextBox {
  hasMoved?: boolean;
  worldPosition?: Point3;
  worldBoundingBox?: {
    topLeft: Point3;
    topRight: Point3;
    bottomLeft: Point3;
    bottomRight: Point3;
    [key: string]: Point3;
  };
  [key: string]: unknown;
}

export interface AnnotationHandles {
  points?: Point3[];
  activeHandleIndex?: number | null;
  textBox?: AnnotationTextBox;
  [key: string]: unknown;
}

export interface AnnotationMeasurementStats {
  length?: number;
  area?: number;
  volume?: number;
  unit?: string;
  [key: string]: unknown;
}

export interface AnnotationData {
  handles?: AnnotationHandles;
  cachedStats?: Record<string, AnnotationMeasurementStats>;
  label?: string;
  contour?: unknown;
  [key: string]: unknown;
}

export interface Annotation {
  annotationUID?: string;
  parentAnnotationUID?: string;
  interpolationUID?: string;
  childAnnotationUIDs?: string[];
  highlighted?: boolean;
  isLocked?: boolean;
  isVisible?: boolean;
  invalidated?: boolean;
  isSelected?: boolean;
  autoGenerated?: boolean;
  metadata?: AnnotationMetadata;
  data: AnnotationData;
}

export interface AnnotationEventDetail {
  annotation: Annotation;
  [key: string]: unknown;
}

